const ADD_JOB= 'ADD_JOB';
const DELETE_JOB= 'DELETE_JOB';
const SET_JOB= 'SET_JOB';
const SET_JOBS= 'ADD_JOBS';
const DELETED_COMPLETED_JOBS= 'DELETED_COMPLETED_JOBS';

export {ADD_JOB, DELETE_JOB, SET_JOB,SET_JOBS, DELETED_COMPLETED_JOBS}