const ADD_JOB= 'ADD_JOB';
const DELETE_JOB= 'DELETE_JOB';
const SET_JOB= 'SET_JOB';
const SET_COMPLETED_JOBS= 'SET_COMPLETED_JOBS';
const DELETED_COMPLETED_JOBS= 'DELETED_COMPLETED_JOBS';
const SET_FILTER= 'SET_FILTER';


export {ADD_JOB, DELETE_JOB, SET_JOB, SET_COMPLETED_JOBS, DELETED_COMPLETED_JOBS, SET_FILTER}